services:
  nginx:
    restart: always
    image: leriugulava/laravel-nginx
  php:
    restart: always
    depends_on:
      - nginx
    image: leriugulava/laravel-php
  mysql:
    image: mysql
    volumes:
      - data:/var/lib/mysql
    env_file:
      - .env
volumes:
  data:
