name: workflow.yml
on:
  push:
    branches:
      - main
      - workflow_dispatch
jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push PHP Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./dockerfiles/php.prod.Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-php:latest
      - name: Push Nginx Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./dockerfiles/nginx.prod.Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-nginx:latest
  deploy:
    needs: push-to-docker
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: SSH into server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            mkdir -p ~/laravel-app
      - name: Create Environment
        run: |
          echo "APP_NAME=Laravel-test" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env

          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

          echo "LOG_CHANNEL=stack" >> .env
          echo "LOG_LEVEL=error" >> .env
      - name: Copy Compose In Production
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.prod.yml,.env'
          target: laravel-app
      - name: Run App
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
              cd ~/laravel-app
              docker compose -f docker-compose.prod.yml pull
              docker compose -f docker-compose.prod.yml up -d
              docker compose -f docker-compose.prod.yml exec -T php php artisan migrate --force
              docker compose -f docker-compose.prod.yml exec -T php php artisan config:cache
              docker compose -f docker-compose.prod.yml exec -T php php artisan route:cache
              docker compose -f docker-compose.prod.yml exec -T php php artisan view:cache
              docker image prune -f




# laravel-test-prod
# 123123123
